INSERT INTO albums VALUES ("1", "Get Rich Or Die Tryin'", "50 Cent", "Rap");
INSERT INTO albums VALUES ("2", "Finally Rich", "Chief Keef", "Rap");
INSERT INTO albums VALUES ("3", "DAMN.", "Kendrick Lamar", "Rap");
INSERT INTO albums VALUES ("4", "2001", "Dr. Dre", "Rap");
INSERT INTO albums VALUES ("5", "Astro World", "Travis Scott", "Rap");
INSERT INTO albums VALUES ("6", "The Infamous", "Mobb Deep", "Rap");
INSERT INTO albums VALUES ("7", "Without Warning", "21 Savage, Offset, Metro Boomin", "Rap");
INSERT INTO albums VALUES ("8", "All Eyez On Me", "2Pac", "Rap");
INSERT INTO albums VALUES ("9", "Culture II", "Migos", "Rap");
INSERT INTO albums VALUES ("10", "Dear Annie", "Rejjie Snow", "Rap");
INSERT INTO albums VALUES ("11", "Burn Dem Bridges", "Skin On Skin", "Techno");
INSERT INTO albums VALUES ("12", "Berlin", "Techno House", "Techno");
INSERT INTO albums VALUES ("13", "Pump Up The Jam", "Technotronic", "Techno");
INSERT INTO albums VALUES ("14", "Der Techno-Club", "Jarow", "Techno");
INSERT INTO albums VALUES ("15", "Is Maith Liom Techno", "An Criu Craiceailte", "Techno");
INSERT INTO albums VALUES ("16", "L'Amour Toujours", "Gigi D'Agostino", "Techno");
INSERT INTO albums VALUES ("17", "Losing It", "FISHER", "Techno");
INSERT INTO albums VALUES ("18", "I Want You (Forever)", "Carl Cox, Josh Butler", "Techno");
INSERT INTO albums VALUES ("19", "TURN ON THE LIGHTS", "BASSTON", "Techno");
INSERT INTO albums VALUES ("20", "Techno Pop", "Kraftwerk", "Techno");
INSERT INTO albums VALUES ("21", "Gawk", "Vundabar", "Indie");
INSERT INTO albums VALUES ("22", "Tigersapp", "Szymon", "Indie");
INSERT INTO albums VALUES ("23", "Fuzzybrain", "Dayglow", "Indie");
INSERT INTO albums VALUES ("24", "Saltwater", "Geowulf", "Indie");
INSERT INTO albums VALUES ("25", "Fade", "Launder", "Indie");
INSERT INTO albums VALUES ("26", "Social Cues", "Cage The Elephant", "Indie");
INSERT INTO albums VALUES ("27", "Naked All The Time", "Sports", "Indie");
INSERT INTO albums VALUES ("28", "Hello, Anxiety", "Phum Viphurit", "Indie");
INSERT INTO albums VALUES ("29", "Buds", "Surf Curse", "Indie");
INSERT INTO albums VALUES ("30", "Spring EP", "Wallows", "Indie");
INSERT INTO albums VALUES ("31", "1989", "Taylor Swift", "Pop");
INSERT INTO albums VALUES ("32", "21", "Adele", "Pop");
INSERT INTO albums VALUES ("33", "x", "Ed Sheeran", "Pop");
INSERT INTO albums VALUES ("34", "In The Lonely Hour", "Sam Smith", "Pop");
INSERT INTO albums VALUES ("35", "thank u, next", "Ariana Grande", "Pop");
INSERT INTO albums VALUES ("36", "Marry Me", "Olly Murs", "Pop");
INSERT INTO albums VALUES ("37", "Sonder", "Dermot Kennedy", "Pop");
INSERT INTO albums VALUES ("38", "CRASH", "Charli XCX", "Pop");
INSERT INTO albums VALUES ("39", "Give Me The Future", "Bastille", "Pop");
INSERT INTO albums VALUES ("40", "Dawn FM", "The Weeknd", "Pop");
INSERT INTO albums VALUES ("41", "The Dark Side of the Moon", "Pink Floyd", "Rock");
INSERT INTO albums VALUES ("42", "Nevermind", "Nirvana", "Rock");
INSERT INTO albums VALUES ("43", "Rumours", "Fleetwood Mac", "Rock");
INSERT INTO albums VALUES ("44", "Ten", "Pearl Jam", "Rock");
INSERT INTO albums VALUES ("45", "Highway to Hell", "AC/DC", "Rock");
INSERT INTO albums VALUES ("46", "Funeral", "Arcade Fire", "Rock");
INSERT INTO albums VALUES ("47", "Van Halen", "Van Halen", "Rock");
INSERT INTO albums VALUES ("48", "Led Zeppelin II", "Led Zeppelin", "Rock");
INSERT INTO albums VALUES ("49", "Revolver", "The Beatles", "Rock");
INSERT INTO albums VALUES ("50", "Moving Pictures", "Rush", "Rock");